Add models
quesiasts/TechStarts-Mktplace pull request #12
Opened 2021-01-13 17:41 UTC by Delismachado

Adicionando models e restruturando nome de aquivos e pastas.

2021-01-13 19:30 UTC, lucasljoliveira-olist requested changes

2021-01-13 19:30 UTC, lucasljoliveira-olist commented on backend/controller/seller_controller.py
> +    log = Log(None, None, f'Seller {seller.name} cadastrado!' )
No caso de atributos que podem receber None coloque-os na model por ultimo, atribuindo = None, como por exemplo:
    def __init__(self, atributo1: str, **_atributo2: str = None, atributo3: int = None_**):

Dessa forma é opcional criar o objeto indicando o atributo1 e atributo2, por exemplo.
Não relacionando-os, como no seu exemplo:
Log(f'Seller {seller.name} cadastrado!')
ou relacionando-os:
Log(f'Seller {seller.name} cadastrado!', None, None)

2021-01-13 19:56 UTC, Delismachado commented
@lucasljoliveira-olist fiz as alterações solicitadas.
Obrigada!

2021-01-14 14:28 UTC, lucasljoliveira-olist approved these changes
Booa Derli, parabéns!!!

2021-01-14 14:31 UTC, JotaCanutto approved these changes

2021-01-14 14:36 UTC, Rafaellynhah approved these changes
Aprovado!

2021-01-14 14:36 UTC, quesiasts approved these changes

2021-01-14 14:47 UTC, merged